---
# tasks file for goofys |  Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and setting up {{ goofys_app }} {{ goofys_version }}
  get_url:
    url: "{{ goofys_dl_url }}"
    dest: "{{ goofys_bin_path }}"
    mode: "{{ goofys_bin_permission_mode }}"
